name: Expense Bot

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 1 * *'    # Retain monthly maintenance run

jobs:
  run-bot:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create credential file
      run: |
        echo '${{ secrets.GOOGLE_CREDENTIALS }}' > credentials.json

    - name: Run bot
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
        GOOGLE_CREDENTIALS_PATH: credentials.json
      run: python src/bot.py

    # Optional: Add a simple notification or logging step
    - name: Log Completion
      if: success()
      run: echo "Expense Bot workflow completed successfully"